version: "3.2"

services:
  watchdog:
    build: .
    image: watchdog_bot:latest
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      TG_TOK:  ${TG_TOK}
      PG_DB:   ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
    networks:
      - db_postgres_net
    logging:
        driver: "fluentd"
        options:
          fluentd-address: "localhost:24224"
          tag: "watchdog"
    container_name: watchdog


networks:
  db_postgres_net:
    external: true
